Full Graph: Graph(num_nodes=111059956, num_edges=1615685872,
      ndata_schemes={'train_mask': Scheme(shape=(), dtype=torch.bool), 'val_mask': Scheme(shape=(), dtype=torch.bool), 'test_mask': Scheme(shape=(), dtype=torch.bool), 'feat': Scheme(shape=(128,), dtype=torch.float32), 'label': Scheme(shape=(), dtype=torch.int32)}
      edata_schemes={})
Num Rels:  1
Feat dim:  128
Converting full graph to long datatype.
Using single format to save memory.
Process Process-1:
Traceback (most recent call last):
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/dgl/multiprocessing/pytorch.py", line 37, in decorated_function
    raise exception.__class__(trace)
RuntimeError: Traceback (most recent call last):
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/dgl/multiprocessing/pytorch.py", line 25, in _queue_result
    res = func(*args, **kwargs)
  File "/home/yw8143/marius_artifact/experiment_manager/baselines/dgl/node_classification.py", line 127, in run
    torch.cuda.set_device(device_id)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.

Process Process-2:
Traceback (most recent call last):
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/dgl/multiprocessing/pytorch.py", line 37, in decorated_function
    raise exception.__class__(trace)
RuntimeError: Traceback (most recent call last):
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/dgl/multiprocessing/pytorch.py", line 25, in _queue_result
    res = func(*args, **kwargs)
  File "/home/yw8143/marius_artifact/experiment_manager/baselines/dgl/node_classification.py", line 127, in run
    torch.cuda.set_device(device_id)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.

Process Process-3:
Traceback (most recent call last):
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/dgl/multiprocessing/pytorch.py", line 37, in decorated_function
    raise exception.__class__(trace)
RuntimeError: Traceback (most recent call last):
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/dgl/multiprocessing/pytorch.py", line 25, in _queue_result
    res = func(*args, **kwargs)
  File "/home/yw8143/marius_artifact/experiment_manager/baselines/dgl/node_classification.py", line 127, in run
    torch.cuda.set_device(device_id)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.

Process Process-4:
Traceback (most recent call last):
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/dgl/multiprocessing/pytorch.py", line 37, in decorated_function
    raise exception.__class__(trace)
RuntimeError: Traceback (most recent call last):
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/dgl/multiprocessing/pytorch.py", line 25, in _queue_result
    res = func(*args, **kwargs)
  File "/home/yw8143/marius_artifact/experiment_manager/baselines/dgl/node_classification.py", line 127, in run
    torch.cuda.set_device(device_id)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
  File "/scratch/yw8143/miniconda3/envs/mariusGNNenv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.

